<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Login.aspx.cs" Inherits="skillExchange.Login" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Sign in | Skill Exchange</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        body{min-height:100vh;margin:0;background:linear-gradient(135deg,#eef4ff 0%,#eafbf8 100%);font-family:Inter,Segoe UI,Arial,sans-serif;color:#172554}.auth-wrap{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:28px}.auth-card{width:100%;max-width:920px;background:#fff;border-radius:24px;overflow:hidden;box-shadow:0 22px 60px rgba(30,64,175,.16);display:grid;grid-template-columns:42% 58%}.auth-intro{background:linear-gradient(145deg,#1e40af,#0f766e);padding:42px 32px;color:#fff;text-align:center;display:flex;flex-direction:column;justify-content:center;align-items:center}.auth-intro h1{font-size:28px;font-weight:700;margin:22px 0 10px}.auth-intro p{color:#dbeafe;line-height:1.7;margin:0}.profile-image{width:172px;height:172px;border-radius:50%;background:#fff;padding:7px;box-shadow:0 12px 30px rgba(0,0,0,.16)}.auth-form{padding:50px}.auth-form h2{font-size:30px;font-weight:700;margin:0 0 8px}.subtext{color:#64748b;margin-bottom:30px}.form-label{font-weight:600;color:#334155}.form-control{border-radius:10px;padding:12px 14px;border-color:#d7deea}.form-control:focus{box-shadow:0 0 0 4px rgba(37,99,235,.12);border-color:#2563eb}.btn-login{border:0;border-radius:10px;padding:12px;font-weight:700;background:linear-gradient(90deg,#2563eb,#0f766e)}.btn-login:hover{background:linear-gradient(90deg,#1d4ed8,#0b665b)}.validator{font-size:.875rem}.register-link{color:#2563eb;font-weight:700;text-decoration:none}@media(max-width:720px){.auth-card{grid-template-columns:1fr;max-width:460px}.auth-intro{padding:28px}.profile-image{width:118px;height:118px}.auth-form{padding:32px 26px}}
    </style>
</head>
<body><form id="form1" runat="server"><main class="auth-wrap"><section class="auth-card"><aside class="auth-intro"><img class="profile-image" src="Content/profile-illustration.svg" alt="Skill Exchange profile illustration" /><h1>Skill Exchange</h1><p>Learn, teach, and grow with a community that shares knowledge.</p></aside><div class="auth-form"><h2>Welcome back</h2><p class="subtext">Sign in to manage your skills and exchange requests.</p><div class="mb-3"><label class="form-label">Email address</label><asp:TextBox ID="txtEmail" runat="server" CssClass="form-control" TextMode="Email" placeholder="name@example.com"></asp:TextBox><asp:RequiredFieldValidator ID="rfvLoginEmail" runat="server" ControlToValidate="txtEmail" ErrorMessage="Please enter your email." ForeColor="Red" Display="Dynamic" CssClass="validator" ValidationGroup="LoginGroup"></asp:RequiredFieldValidator><asp:RegularExpressionValidator ID="revLoginEmail" runat="server" ControlToValidate="txtEmail" ErrorMessage="Please enter a valid email address." ForeColor="Red" Display="Dynamic" CssClass="validator" ValidationExpression="^[^@\s]+@[^@\s]+\.[^@\s]+$" ValidationGroup="LoginGroup"></asp:RegularExpressionValidator></div><div class="mb-4"><label class="form-label">Password</label><asp:TextBox ID="txtPassword" runat="server" CssClass="form-control" TextMode="Password" placeholder="Enter your password"></asp:TextBox><asp:RequiredFieldValidator ID="rfvLoginPassword" runat="server" ControlToValidate="txtPassword" ErrorMessage="Please enter your password." ForeColor="Red" Display="Dynamic" CssClass="validator" ValidationGroup="LoginGroup"></asp:RequiredFieldValidator></div><asp:Button ID="btnLogin" runat="server" Text="Sign in" CssClass="btn btn-primary btn-login w-100" OnClick="btnLogin_Click" ValidationGroup="LoginGroup" /><div class="text-center mt-4"><span class="text-secondary">New to Skill Exchange?</span> <a class="register-link" href="Register.aspx">Create an account</a></div><asp:Label ID="lblMessage" runat="server" ForeColor="Red" CssClass="d-block text-center mt-3"></asp:Label></div></section></main></form></body>
</html>
